### ISSUE TITLE
extra space added.

### ISSUE THREAD

**Issue by paulirish** [Microsoft/vscode-comment#11]
Repro:
Have a class function like:
```js
  static makeV1TableHeadings(headings) {

  }
```

Run "Add doc comments." 
View the result:
```js
  /**
   * @param  {} headings
   */
``` 

Note there's an extra space before the curly brackets.

**Comment by egamma** [comment]
@paulirish I suggest to use built-in JSDoc generation support

![jsdoc](https://cloud.githubusercontent.com/assets/172399/25274626/3abf6316-2691-11e7-96df-d45f7e310e2e.gif)

**Comment by paulirish** [comment]
not bad!! alright then, works for me. :)

**Comment by paulirish** [comment]
The JSDoc snippet does generate some trailing whitespace, however. :)
