### ISSUE TITLE
Comment isn't properly indented

### ISSUE THREAD

**Issue by mathias-lundin** [Microsoft/vscode-comment#2]
Generated comments are not indented the same as the function.

``` javascript
/**
 * @param  {any} someParam
 */
        function myFunc(someParam) {
            return true;
        }
```

**Comment by stevencl** [comment]
Thanks for reporting, I'll take a look and see what I can do.

**Comment by stevencl** [comment]
I pushed a fix in commit 20d8bd. I simply count the number of leading whitespace characters in the line containing the function signature and then indent the comment with the same number of spaces.

I'll close this issue but please let me know if the fix doesn't work as you expect it to.
