### ISSUE TITLE
Add support for TypeScript interfaces, and ES6 classes and methods

### ISSUE THREAD

**Issue by joeskeen** [Microsoft/vscode-comment#3]
This plugin has limited use for TypeScript users that use interfaces and ES6 class syntax.  Adding this would be great!
Related to #1

**Comment by joewood** [comment]
+1 - would be great if this worked on member functions

**Comment by tgfjt** [comment]
+1

**Comment by stevencl** [comment]
I agree. I'll happily accept pull requests :-)

**Comment by stevencl** [comment]
Another similar extension is available, Document This, which is more powerful,
