### ISSUE TITLE
no idea how to add a signature and cannot use the package

### ISSUE THREAD

**Issue by ta3pks** [Microsoft/vscode-comment#5]
no idea how to add a signature and cannot use the package

**Comment by stevencl** [comment]
Sorry you were having difficulties. Can you add more information about what wasn't working?

Incidentally, the extension is quite limited and only works with function signatures. There is another extension available, Document This which supports many more tags.

**Comment by stevencl** [comment]
I'm going to close this issue just now but feel free to reopen it and describe what wasn't working.
