### ISSUE TITLE
{any} is not helpful. I'd rather want empty {}

### ISSUE THREAD

**Issue by wooramy** [Microsoft/vscode-comment#6]
For parameters without types, it adds {any} but it's rather cumbersome to delete `any` first and then type.

Please consider just adding empty {} for unknown types. Thanks!

**Comment by stevencl** [comment]
Thanks for the suggestion. I've updated the extension accordingly. See commit https://github.com/Microsoft/vscode-comment/commit/93a53c5c6a0b614a8610ebcaff36065ea613a7cb

**Comment by wooramy** [comment]
Wow, thanks for fixing the issue so fast. Thanks again!
