### ISSUE TITLE
Error loading the extension

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode-comment#7]
https://marketplace.visualstudio.com/items?itemName=stevencl.addDocComments
![image](https://cloud.githubusercontent.com/assets/8189808/16984813/a9cc2ed0-4e7c-11e6-88b8-2fb1d269be5e.png)

The Extension is causing an error
![image](https://cloud.githubusercontent.com/assets/8189808/16984831/b85e3eac-4e7c-11e6-9760-1586005b3e39.png)

**Comment by stevencl** [comment]
Unfortunately I can't repro this. I only have the vscode-comment extension installed and I do not see any errors showing up in the console. I don't make any calls to publishDiagnostics in my code.

**Comment by ghost** [comment]
Hmm, can it be some conflict with another extension? Which would be really hard to find.

**Comment by stevencl** [comment]
Do you see the error if the vscode-comment extension is the only extension installed?

**Comment by ghost** [comment]
Hmm no with only the extension installed I don't get the error, now that is weird

**Comment by stevencl** [comment]
Closing as per your comment in this issue: https://github.com/Microsoft/vscode/issues/9522#issuecomment-233938748
