### ISSUE TITLE
Make keyboard shortcut configurable

### ISSUE THREAD

**Issue by elcojacobs** [Microsoft/vscode-comment#8]
I'd love to use this extension, but CTRL-ALT-D is mapped to switching desktops on Ubuntu. 
I understand that any shortcut would clash for someone, so would it be possible to make the shortcut configurable in the workspace settings?

**Comment by stevencl** [comment]
I think you maybe meant this for the Document This extension instead? It uses crtl-alt-d to generate doc comments.

**Comment by elcojacobs** [comment]
Oops, sorry about that. I had multiple tabs open looking for alternatives.
