### ISSUE TITLE
Document on tab completion

### ISSUE THREAD

**Issue by brendo** [Microsoft/vscode-comment#9]
I'm a Sublime Text user, and one of the remaining features that's stopping the switch to VSCode for me is the [DocBlockr](https://github.com/Warin/Sublime/tree/master/DocBlockr) extension.

It's essentially the same as this plugin, but it can be invoked from pressing `TAB` after `/**`:

```
/**tab
function say(word) {
    return word;
}
```

becomes:

```
/**
 * @param word
 * @return string
 */
function say(word) {
    return word;
}
```

Would it be possible to add this 'tab to complete' functionality to this extension for VSCode?

**Comment by waderyan** [comment]
@brendo can you try [Document This](https://marketplace.visualstudio.com/items?itemName=joelday.docthis)? I was also a big fan of DocBlockr and I've found Document this to meet my needs. 

@joelday is an excellent extension author and would be happy to hear your feedback if anything is missing from his extension.

**Comment by joelday** [comment]
Thanks @waderyan! @brendo, make sure to look at the available settings if the default behavior isn't to your liking. Let me know if you have any issues. Thanks!

**Comment by brendo** [comment]
Ah great! I tried Document This prior to the 0.3.0 release which looks like it added this functionality. Thanks for the reminder to check it out again.
